### ISSUE TITLE
Caption buttons no longer seem to change variants

### ISSUE THREAD

**Issue by funn-hue** [Maplespe/DWMBlurGlass#106]
I might be wrong, but I think that in the previous version it used to change the glyph color depending on the blend color, but now it doesn't seem to do that
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/7202122a-b9a6-4255-b550-daf2da8a5e92)

there's also an issue with the top 1px border not being rendered, or not using the blend color (can be noticed in chrome) 
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/4fb803c5-95d1-4969-a176-120c0f4330cf)

it shows in uwp apps, but it's like too much transparent or something 
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/8917cb02-f316-409b-ae84-88582c06e879)

**Comment by nopahc4** [comment]
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/5c6755e7-5f78-4c13-8caf-bd714f11639c)
I also noticed aero peek is also coloured, but I don't think it should be like that

**Comment by TheInsane101** [comment]
I also noticed aero peek is coloured, but I don't think it should be like that

I like it; it's really cool that they pulled that off. I wonder if they could make it another togglable option for those looking for the most 1:1 imitation of 7.

**Comment by nopahc4** [comment]
> I also noticed aero peek is coloured, but I don't think it should be like that
> 
> I like it; it's really cool that they pulled that off. I wonder if they could make it another togglable option for those looking for the most 1:1 imitation of 7.

true

**Comment by Maplespe** [comment]
The borderline issue has been fixed in the new version.

**Comment by nopahc4** [comment]
> The borderline issue has been fixed in the new version.

just noticed my reply didnt send lol, its still kinda broken
![image](https://github.com/Maplespe/DWMBlurGlass/assets/152728509/0bf2b880-a05d-46a1-94e6-a3ef33503f7d)
with extend effect to borders off, only the right and bottom border appear, the left and top is transparent, and the right frame becomes thick when the app is closing, with enabled extend effect to borders they render correctly but then the thick ones appear when the app is closing. I believe all issues with the borders is due to microsoft being funny and removing the active border from the atlas image, and it renders them a different way, on older 10 builds for example the border was from the accent color, and in newer its black, all builds only have the inactive frame in the atlas

**Comment by funn-hue** [comment]
Closing this since issues seem to be fixed for a long time now
