### ISSUE TITLE
safely for using on bare metal main machine

### ISSUE THREAD

**Issue by cookies5219** [Maplespe/DWMBlurGlass#132]
is it safe to use on my main pc or is it recommend for being used in vms or anything that isnt my main pc

**Comment by ALTaleX531** [comment]
DwmBlurGlass doesn't modify your system files, it only patches the memory of the dwm process, and it only runs once on boot, which means that even if DwmBlurGlass causes a crash it won't affect your daily use. Instead of asking questions here, I think it would be better to try it yourself in a virtual machine.
