### ISSUE TITLE
Add unloaddll argument

### ISSUE THREAD

**Issue by Umbrella-TEC** [Maplespe/DWMBlurGlass#152]
Add the unloaddll argument to disable transparency via the console.

**Comment by ALTaleX531** [comment]
As you can see, @ephemeralViolette has already implemented this feature, but before merging it, I'm a bit curious as to why it was implemented, was it to make it easier to install the winhawk mods or something else? Personally, I don't feel it's quite necessary, because this can also be done by clicking the uninstall button.
Of course, the merging operation is in charge of @Maplespe, I don't decide anything.

**Comment by ephemeralViolette** [comment]
The GUI is unavailable if you're a third party compiling this, so this avoids having to restart the DWM process entirely. (You also need to make the injector application only compile the command line parts, which I did in the master branch of my fork.)

I thought it was a harmless change to submit because the `loaddll` option already existed without any counterpart.

**Comment by Umbrella-TEC** [comment]
I requested this feature because I can turn transparency on and off via the desktop context menu. This command will make turning off transparency more correct.

**Comment by ALTaleX531** [comment]
Looks like this needs further confirmation from @Maplespe.

**Comment by ephemeralViolette** [comment]
I will weigh in with my opinion - I think that this is a good feature to implement too. There are legitimate reasons (as mentioned above) to include such a feature, and I don't think that it would be a particularly useful feature for people wishing to repackage the software to utilise in any case. The `loaddll` option itself is much more useful in that case, since anyone could automate installation of DWMBlurGlass simply by creating a scheduled task to load that at startup.

Some other use cases could be (with additional third-party scripts):
- Turning off when certain software is open (i.e. a video game)
- Turning off when power settings change (i.e. laptop is low on battery)

**Comment by Maplespe** [comment]
I'm going to follow the "System Settings - Personalization - Colors - Enable Transparency" option in the next version to make it consistent with the system's transparency.

**Comment by teknixstuff2** [comment]
> As you can see, @ephemeralViolette has already implemented this feature, but before merging it, I'm a bit curious as to why it was implemented, was it to make it easier to install the winhawk mods or something else? Personally, I don't feel it's quite necessary, because this can also be done by clicking the uninstall button. Of course, the merging operation is in charge of @Maplespe, I don't decide anything.

This would be useful, since unloading and then loading again would reload the config file, without having to kill DWM.

**Comment by edivanbaptista** [comment]
Edivan Baptista.

Eu sou do Brasil (Language Portorgue BR);

E seu trabalho, chegou até nós! Parabéns, você muito talentoso...

Na próxima, coloque também no modo automático, as cores (Inactive Title Bars Color - mode automatic)!

Tem como no ato do iniciar do Windows, autorizar automatic or  Simbol... (...) Felicitaria, e muito  a Vida, nas atualizações do Update!

Um Forte Abraço.

**Comment by edivanbaptista** [comment]
Edivan Baptista - edivan.baptista@gmail.com

**Comment by ALTaleX531** [comment]
@edivanbaptista If you wish to make a feature request, please open a new issue instead of posting a comment in an already resolved issue, otherwise your request will be ignored.
Also, you don't need to leave your email, our conversations will only take place on Github unless your privacy is involved.

**Comment by edivanbaptista** [comment]
![Sem título](https://github.com/Maplespe/DWMBlurGlass/assets/40346205/723abbfa-0917-45f1-8a78-a4d32a0fd2da)

Desculpe-me, sou novo por aqui.... Está dado este erro....

**Comment by SandTechStuff** [comment]
This seems to be a problem caused by a Windows 11 update as shown in this issue: #324

As ALTaleX said, you should make a new issue if you have further problems or questions, the community will be happy to help. 🙂

**Comment by edivanbaptista** [comment]
Voltou a funcionar... Muito obrigado.

Espero que as cores inativas da barra de titulo (Inative Title Bars Color)  , seja automática...  na próxima versão.... E algum dispositivo automático d e atualização dos Simbols... Um Forte Abraço.
