### ISSUE TITLE
Command-line only compilation mode for third-parties

### ISSUE THREAD

**Issue by ephemeralViolette** [Maplespe/DWMBlurGlass#191]
**Describe the solution you'd like**
> A compiler define should be added for the injector application to conditionally compile the GUI (based on private MiaoUI library) or just a command-line only version.

**Your reason (tell us why we need it)**
> It is stated in the dependencies section of the README document "[s]ince the GUI program uses private libraries, only insiders can compile the GUI, which does not affect the compilation of the libraries", which is misleading.
>
> The GUI program is not just a GUI, but a general controller application, and it shares memory (i.e. symbols) with the extension which is required to initialise it. For example, you cannot write up a Windhawk mod to LoadLibrary the extension into DWM. Because of statically-linked information, you often can't swap the extension DLL with a prebuilt copy of the GUI either.

**Describe alternatives you've considered**
> I have a personal fork that removes the GUI portions, but it's a little messy: https://github.com/ephemeralViolette/DWMBlurGlass-FixedGUI

**Additional context**
> (I don't think that additional context is necessary)

**Comment by Maplespe** [comment]
First of all, the code is complete and you can indeed compile the command line only version and run it correctly right?
But normal users don't need the command line and don't manipulate these parameters via the command line, this is for developers, but since the code is complete, developers have their own ways to make it work, just like the code you modified.

I have explained in #24 why I don't add an unattended command line.
Regular users don't need it, and most people are only there to utilize it into their own paid programs or integration packages or iso images.

I certainly can't stop other people from doing what they want with the code, so I'm not going to add official support.
People can certainly choose other 3rd party mods, but I will not be responsible for any of their 3rd party mods.
