### ISSUE TITLE
1809 support

### ISSUE THREAD

**Issue by arukateru** [Maplespe/DWMBlurGlass#202]
**Describe the solution you'd like**
1809 support

**Your reason (tell us why we need it)**
Even though Glass8 by big muscle exists on 1809, it does not provide any support for the Aero high contrast inactive effect nor does it support setting different color opacities for inactive windows.  So the only option is to use very little color for the active window, or deal with ugly gray color on inactive windows when the glass is over a dark surface.

**Describe alternatives you've considered**
BlurBalance option in Glass8 comes with many problems like ugly animations, too high colors intensity, and others.

**Additional context**
I would donate $15 to this project via the Ko-fi link if 1809 support is added and there is the option to reinject into DWM if DWM crashes.

**Comment by black-ish** [comment]
+1
I also still use 1809 LTSC and would like to see support for it.

**Comment by ALTaleX531** [comment]
So why not just upgrade to 22H2 instead of staying at 1809, any advantages? 🤔

**Comment by arukateru** [comment]
> So why not just upgrade to 22H2 instead of staying at 1809, any advantages? 🤔

Yes, 2 main things. The first is that the performance is a bit better in many aspects. The second is that 1809 is much better for Windows 7 modding for those who care about security updates. In 22H2, many files are needlessly changed frequently in updates to files important for the Windows 7 modding. In 1809, updates very rarely ever break any modding.

**Comment by Maplespe** [comment]
We can't be compatible only for 1809, which would mean additional maintenance of versions 1809, 1903, 1909. Besides, most of the users below version 2004 are old users of glass8, including the unreleased AWM which also advertises support for 1809.
So this obviously this doesn't do us much good, in my opinion.

**Comment by TheInsane101** [comment]
Tbh I'd rather still use glass8. DWMBG is not there yet, mainly for four _big_ reasons that matter _way_ more to me than whether the blur type is a perfect clone: the colour being able to be changed by the system colour, and being able to affect the start menu and taskbar. glass8 adds the reflection effect and same blur to those components, and since DWMBG _doesn't_ do that, it makes the effect inconsistent. Lastly, you can adjust the opacity of the reflection in glass8, apply your own reflection images through the GUI, and apply your own caption themes directly without an msstyles theme. If the above is added to either DWMBG or AWM, only then will I consider glass8 obsolete.
