### ISSUE TITLE
Only Half of Reflections appearing

### ISSUE THREAD

**Issue by TheDolphinSlayer** [Maplespe/DWMBlurGlass#22]
The new update from issue #18 is way more stable! On explorer window the reflection is perfect!

But for some 

https://github.com/Maplespe/DWMBlurGlass/assets/73983610/f870c5d8-9203-44ba-9eef-0b91b0702607

reason the taskbar + apps like OBS and the animation program i'm using only shows half? Not sure if its due to the windows 7 api? I only say that cause the explorer window and task manager handle the reflection perfectly

-I promise i'm not trying to be ungrateful, I am so grateful for everything you're doing, the fact its free, and how you're listening to feedback. seriously thank you!-

**Comment by Maplespe** [comment]
Please check out the new version.

**Comment by NotJorrd** [comment]
I have noticed that the reflections work on my primary monitor (I am only referring to the taskbar) and not the second monitor, as far as the actual windows go, its mostly okay but when you drag the window to the far left until it touches the edge, the reflections stop moving all together

(my primary monitor is on the left, the second one is on the right)

if you have a window inside the second monitor and drag it slightly into the primary one, the reflections instantly disappear on the right side of the window since it's inside the secondary monitor and will appear only on the left side of the window that is inside the primary monitor.

![image](https://github.com/Maplespe/DWMBlurGlass/assets/156122285/901e70c6-3f12-4425-ab43-6882c765e269)

**Comment by Maplespe** [comment]
I seem to have explained this before, due to the inconsistent scaling ratios and resolutions and alignments of the individual monitors, I can only create an Aero reflection basemap for each monitor individually, so that only if the window is fully located on the target monitor will the corresponding image be displayed.
It's not possible to create a bitmap that covers the total combined resolution of the entire monitor, this is for performance reasons.

Additionally, the problem of incomplete display of the bottom image of some windows on a single monitor should be fixed.
