### ISSUE TITLE
Command line/Silent Install

### ISSUE THREAD

**Issue by teknixstuff** [Maplespe/DWMBlurGlass#24]
Any chance of adding a silent install/uninstall flag?
eg `-install` to install and `-uninstall` to uninstall?

**Comment by Maplespe** [comment]
I'm not going to add an unattended install option, I don't want my program to be exploited or become part of other software that they can't contribute anything to except changing the name to other commercial software. Because my other programs have this precedent .


Also since the program depends on symbols and the download usually takes a long time, the lack of any hints in it can trigger annoyance in the user.

Thanks, I hope you understand.

**Comment by Maplespe** [comment]
Of course, if you really need it, the code is open source and you can implement a loader yourself by referring to the GUI code.
