### ISSUE TITLE
[FEATURE] DWMBG effects on entire window area

### ISSUE THREAD

**Issue by Undisputed00x** [Maplespe/DWMBlurGlass#254]
Could be there a feature to make effects of DWMBG expanded to entire window by using [DwmExtendFrameIntoClientArea](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmextendframeintoclientarea). 
Although this project is about windows titlebar and there is [EBM ](https://github.com/Maplespe/ExplorerBlurMica)which does that but unfortunately only for explorer. 
Also i guess that probably there are plans for future projects judging from discussions in your projects which will implement new features but not so sure about it. Anyways thank you for these FOSS amazing mods, you and AlTaleX are the most proficient about Windows UI

examples below
(Used MFE only for enabling the function mentioned before, effects are rendered entirely by DWMBG)
<details><summary>Details</summary>
<p>

![Screenshot 2024-04-08 024349](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/e8c75ce4-9415-4435-9293-8fa4b1e1fad3)
![Screenshot 2024-04-08 024158](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/ffea5b8a-797e-4403-8830-80df93f2afbd)
![Screenshot 2024-04-08 024428](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/9dcfb657-6c04-46d9-b447-15a20cb21d67)
![Screenshot 2024-04-08 024456](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/99710c20-4f25-4289-9c3f-6cc7f469ab38)

![Screenshot 2024-04-08 031414](https://github.com/Maplespe/DWMBlurGlass/assets/80290008/9ccc7ea8-72e0-4a49-b12c-28a34fccdabf)

</p>
</details>

**Comment by Maplespe** [comment]
You should be able to notice that this API causes content alpha exceptions within the client area, which is disastrous for applications that don't support alpha. This is why a separate EBM project is needed to fix various rendering alpha exceptions for various components for the file explorer in order to achieve perfect transparency.
This is not noticeable in dark, once you switch to light mode the rendered content is almost unreadable.

If it was really that good, we would have done it a long time ago.
