### ISSUE TITLE
Aero reflections while using snip tool

### ISSUE THREAD

**Issue by NotJorrd** [Maplespe/DWMBlurGlass#26]
I'm unable to provide a screenshot, but if you use the snipping tool to screenshot something, the aero reflection appears inside the selection box, it also cuts of at a certain point so it looks really off.

**Comment by Maplespe** [comment]
You will need to provide more information and make sure you are using the latest version.
Because the test didn't show any problems with either the new version of snipping or the old version of the snipping tool.
![145229](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/d567a4c0-566e-4a61-962c-9a67cf359a48)
![145330](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/cf01971f-3b58-4477-9ecc-2c02e6e1ff01)

**Comment by NotJorrd** [comment]
i was using the latest version, i'm not seeing it right now which i find odd, but i'll update if it happens again. if it happens again then it seems to be happening SOMETIMES

**Comment by NotJorrd** [comment]
It happened again, but this time i know how to reproduce it. I haven't tried it with any other window, but I was using Citra Emulator when it happened. This is very specific but it happened when I was in a game and when the window was active. I did the Win + Shift + S to use snip and it happened. When the window is inactive it no longer happens. This also doesn't happen for every window.
