### ISSUE TITLE
When the taskbar is on the side, aero peek gets dislocated

### ISSUE THREAD

**Issue by Asad-13** [Maplespe/DWMBlurGlass#277]
**Describe the bug**
> A clear and concise description of what the bug is:

When the taskbar is on the default bottom position, the aero peek is perfectly located where the window is. But when I have the taskbar on the side, the aero peek effect is shifted from the actual position of the window, and gets cut-off.

**To Reproduce**
> Steps to reproduce the behavior:
1. Have the taskbar at the side, eg left of your screen.
2. Hover the mouse at the show desktop button to enable aero peek.

**Screenshots**
> If applicable, add screenshots to help explain your problem:

(Position of window)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87184327/272b8355-f89a-4a85-824b-9c1c1585c453)

(Position of aero peek)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/87184327/607c97e4-3a6e-4ebc-afb9-c43778b2f03c)

**Additional information (please complete the following information):**
 > OS Version : Windows 10 22H2 19045.4291
 > Software Version : (Assuming this is for DWMBG version) 2.1.1

**What other third-party software do you use:**
> SecureUXTheme
> aero10 from DeviantArt
> OldNewExplorer 
> Windhawk + aerexplorer

**Additional context**

**Comment by ALTaleX531** [comment]
Bug of Windows 10, ask MS to fix it.

**Comment by ALTaleX531** [comment]
See [aero-peek-issue](https://github.com/microsoft/Windows-Dev-Performance/issues/12).
This problem happens even without using DwmBlurGlass, it has been fed back several times but Microsoft just ignored them. Developing and fixing bugs has taken up a large portion of our free time, and we've received so many bug reports that are not caused by DwmBlurGlass. Obviously, it's impossible to explain in detail what's going on with all of them, because no one wants to waste their time on something unrelated.
