### ISSUE TITLE
Laggy window movements when moving non-resizable windows

### ISSUE THREAD

**Issue by Cynosphere** [Maplespe/DWMBlurGlass#31]
https://github.com/Maplespe/DWMBlurGlass/assets/1606710/5b5881c9-7766-4f62-8831-53886fc225b2

**Comment by Cynosphere** [comment]
Okay apparently this isn't noticable in the recording but it is very apparent on 144Hz monitors.

**Comment by Maplespe** [comment]
This issue is consistent with the previously mentioned #12 and #18, this project uses a fuzzy class inside of dwm, which is a problem caused by an inefficient implementation inside of Microsoft.
We are working on a way to try to rewrite the new fuzzing method to solve the problem, which is very complex and requires a long time of reverse analysis and testing.

**Comment by Maplespe** [comment]
Resolved in the new version.
