### ISSUE TITLE
Close, Maximise and minimise buttons are black on third party apps Dark Mode

### ISSUE THREAD

**Issue by mofftty** [Maplespe/DWMBlurGlass#322]
On Windows 11 Dark mode the top 3 buttons on the right are black

On Windows 11 Dark mode the top 3 buttons on the right are black and that is an issue since I use dark mode and I have black wallpaper, it is difficult to see the buttons. However on File Explorer and control panel on Windows 11 works fine since the buttons are white. On other party apps they are black.

File Explorer and Control Panel:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/107669392/df365fc3-af18-4333-9abf-5bb0d12da7e0)![file explor](https://github.com/Maplespe/DWMBlurGlass/assets/107669392/97a2200a-8d56-4386-b6d8-a4be621dd7c4)
![image](https://github.com/Maplespe/DWMBlurGlass/assets/107669392/c72646a2-0ab3-4eed-a530-e5363fe0cb4d)

Winver and other third party apps:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/107669392/f2470550-5710-4a23-879e-9a3fe4152a1f)![image](https://github.com/Maplespe/DWMBlurGlass/assets/107669392/2ab0d6bb-fe22-4ece-b988-2567b6e5e3c1)
Side by Side comparison:
![image](https://github.com/Maplespe/DWMBlurGlass/assets/107669392/3e7fc2ef-98e1-46e5-b741-a50e53814fa2)

Also this is not relevant but can you make aero glass for the taskbar? It would be appreciated it you can!

**Comment by Maplespe** [comment]
It's not a bug, it's mentioned in #279.
Whether or not the title bar supports Dark is up to the application, and even if you don't use DWMBlurGlass, the title bar colors and buttons in those applications are Light because they don't support Dark mode.
File Explorer itself supports Dark mode, so its colors are correct.

Also to enable glass or reflections in the taskbar, use StartIsBack and set its blur to “Blur” and check “Override AccentBlur” in the DWMBlurGlass settings.
