### ISSUE TITLE
DWMBlurGlass marked as threat by Windows Defender

### ISSUE THREAD

**Issue by craftnut** [Maplespe/DWMBlurGlass#54]
Hi, DWMBlurGlass can be marked by Windows Defender as threat "Win32/DefensiveEvasion", obviously, we can just allow the "threat" as it is a false positive, but it would be nice if we didn't have to.
Is there a way to fix this? Or is this just a consequence of modifying system functions on Windows?
![threat](https://github.com/Maplespe/DWMBlurGlass/assets/61483322/b8ef9935-1943-43a7-8aa1-25db0c2e91ed)

**Comment by Maplespe** [comment]
Obviously, almost all landscaping software is misreported.
We can't apply for a certificate security officially, and apparently Microsoft won't issue one, the software requires administrator privileges and memory injection, and doesn't modify system files per se.
I think it is caused by permissions and memory modifications, including injection into system processes (dwm). This cannot be avoided.

**Comment by craftnut** [comment]
Ah, that's what I had thought, but I figured I'd report just in case.
Thanks for the reply nonetheless!
