### ISSUE TITLE
Custom blur method?

### ISSUE THREAD

**Issue by windowsxp3790** [Maplespe/DWMBlurGlass#7]
A Custom blur method would allow for way better performance
Idk if you've looked into that before or not
Glass8 used a custom method

**Comment by ALTaleX531** [comment]
I suggest you give up on the idea of changing the blur type, glass8 becomes corrupted after every Windows update, that's what happens when you use a custom blur method, it becomes unstable and there is no room for the developers to continue to maintain it. Personally, I think DWMBlurGlass was created in the hope of getting a stable glass effect, not to be the next glass8...

**Comment by arukateru** [comment]
Glass8 has good performance because it uses a custom shader. Explorer blur and acrylic blur have comically inefficient shaders and that's why they are laggy. Glass8 breaks after certain Windows updates because DWM functions get changed sometimes, and I don't know much about how Glass8's custom shader works or if it relies on DWM functions, but either way, a custom shader does not HAVE to rely on DWM functions.

**Comment by Maplespe** [comment]
In fact before 1809 everything seemed to work fine, I don't know what Microsoft did to make it so inefficient now, it would take quite a bit of time to investigate and analyze, but I don't have that much time. So the performance issue is not necessarily going to be solved anytime soon.

But adding the Acrylic effect will only make performance worse as it is completely unusable!

**Comment by Maplespe** [comment]
>Glass8 has good performance because it uses a custom shader. Explorer blur and acrylic blur have comically inefficient shaders and that's why they are laggy. Glass8 breaks after certain Windows updates because DWM functions get changed sometimes, and I don't know much about how Glass8's custom shader works or if it relies on DWM functions, but either way, a custom shader does not HAVE to rely on DWM functions.

Incidentally, customizing effects is not possible without DWM's internal functions, and there is little compatibility if you customize effects.
Also from what I've found dwm internal blur uses D2D's built in Effect and it's shader performance itself isn't that bad it's very efficient. I think it's something else, because in Win7 the performance is very good.

**Comment by arukateru** [comment]
This is interesting information. There is still a dwm internal blur in Windows 10's DWM? Btw, yes acrylic has horrible performance when dragging windows, but it seems that when disabling "show window contents while dragging" the performance is fine because it does not try to render the contents until it stops being dragged. Some people may perfer this option as explorer blur, however, for some reason, keeps rendering regardless of whether the window contents are being shown or not, unlike acrylic.

**Comment by Maplespe** [comment]
> This is interesting information. There is still a dwm internal blur in Windows 10's DWM? Btw, yes acrylic has horrible performance when dragging windows, but it seems that when disabling "show window contents while dragging" the performance is fine because it does not try to render the contents until it stops being dragged. Some people may perfer this option as explorer blur, however, for some reason, keeps rendering regardless of whether the window contents are being shown or not, unlike acrylic.

The BlurBehind class existed in Win10.
After Win11 22H2, Microsoft removed it, leaving only the AcrylicBlurBehind class.
![3 W__`N)`BT @TZZ9XD8IL](https://github.com/Maplespe/DWMBlurGlass/assets/43676879/ce20df92-c759-4e12-ba2d-259312fb1369)

**Comment by windowsxp3790** [comment]
> > This is interesting information. There is still a dwm internal blur in Windows 10's DWM? Btw, yes acrylic has horrible performance when dragging windows, but it seems that when disabling "show window contents while dragging" the performance is fine because it does not try to render the contents until it stops being dragged. Some people may perfer this option as explorer blur, however, for some reason, keeps rendering regardless of whether the window contents are being shown or not, unlike acrylic.
> 
> The BlurBehind class existed in Win10. After Win11 22H2, Microsoft removed it, leaving only the AcrylicBlurBehind class. ![3 W__N)BT @TZZ9XD8IL](https://private-user-images.githubusercontent.com/43676879/297292336-ce20df92-c759-4e12-ba2d-259312fb1369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDg3NzIsIm5iZiI6MTcwNTUwODQ3MiwicGF0aCI6Ii80MzY3Njg3OS8yOTcyOTIzMzYtY2UyMGRmOTItYzc1OS00ZTEyLWJhMmQtMjU5MzEyZmIxMzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2E5Mzk1YjQ4NzFiMjU4YjU4YmUwYjhjMWRmMWRiMWQyZWEwYTI5YmViYzg1NzFjZjUxYjU1YzUzY2VlN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C8EDkIuf2JsZ03PbtpnJbrxOzdn6hOBaIM1r6pKdnhg)

so are you gonna look into having a custom shader/blur method or no?

**Comment by catneptune** [comment]
> > > This is interesting information. There is still a dwm internal blur in Windows 10's DWM? Btw, yes acrylic has horrible performance when dragging windows, but it seems that when disabling "show window contents while dragging" the performance is fine because it does not try to render the contents until it stops being dragged. Some people may perfer this option as explorer blur, however, for some reason, keeps rendering regardless of whether the window contents are being shown or not, unlike acrylic.
> > 
> > 
> > The BlurBehind class existed in Win10. After Win11 22H2, Microsoft removed it, leaving only the AcrylicBlurBehind class. ![3 W__N)BT @TZZ9XD8IL](https://private-user-images.githubusercontent.com/43676879/297292336-ce20df92-c759-4e12-ba2d-259312fb1369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDg3NzIsIm5iZiI6MTcwNTUwODQ3MiwicGF0aCI6Ii80MzY3Njg3OS8yOTcyOTIzMzYtY2UyMGRmOTItYzc1OS00ZTEyLWJhMmQtMjU5MzEyZmIxMzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2E5Mzk1YjQ4NzFiMjU4YjU4YmUwYjhjMWRmMWRiMWQyZWEwYTI5YmViYzg1NzFjZjUxYjU1YzUzY2VlN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C8EDkIuf2JsZ03PbtpnJbrxOzdn6hOBaIM1r6pKdnhg)
> 
> so are you gonna look into having a custom shader/blur method or no?

want it so bad just use glass8

**Comment by not-nullptr** [comment]
@windowsxp3790 in the kindest way possible, this project isn't awm and isn't trying to be awm

**Comment by Maplespe** [comment]
And in fact AWM uses dwm's internal blur and not a custom shader.

**Comment by windowsxp3790** [comment]
> @windowsxp3790 in the kindest way possible, this project isn't awm and isn't trying to be awm

i never said it was
nor do i want it to compete with it 
im just saying it would be cool to get a custom blur shader
same with AWM

**Comment by Maplespe** [comment]
We've got this on the agenda, but aren't sure exactly when we'll get it done, and reverse analyzing and testing it is a complicated and painful thing to do.

**Comment by not-nullptr** [comment]
^ especially if you want it to be 100% accurate to windows 7. glass8 just had a basic blur but windows 7 multiplies colours, it's a messy thing and probably very tricky to get right

**Comment by Maplespe** [comment]
has been implemented in the new version.
